// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_SkiaSharp_DrawnUi_WinUI_Native_0_H
#define WINRT_SkiaSharp_DrawnUi_WinUI_Native_0_H
WINRT_EXPORT namespace winrt::Windows::Foundation
{
    struct Size;
}
WINRT_EXPORT namespace winrt::Windows::Foundation::Collections
{
    struct PropertySet;
}
WINRT_EXPORT namespace winrt::Windows::Storage::Streams
{
    struct IBuffer;
}
WINRT_EXPORT namespace winrt::SkiaSharp::DrawnUi::WinUI::Native
{
    struct IBufferExtensionsStatics;
    struct IPropertySetExtensionsStatics;
    struct BufferExtensions;
    struct PropertySetExtensions;
}
namespace winrt::impl
{
    template <> struct category<winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics>{ using type = interface_category; };
    template <> struct category<winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics>{ using type = interface_category; };
    template <> struct category<winrt::SkiaSharp::DrawnUi::WinUI::Native::BufferExtensions>{ using type = class_category; };
    template <> struct category<winrt::SkiaSharp::DrawnUi::WinUI::Native::PropertySetExtensions>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::SkiaSharp::DrawnUi::WinUI::Native::BufferExtensions> = L"SkiaSharp.DrawnUi.WinUI.Native.BufferExtensions";
    template <> inline constexpr auto& name_v<winrt::SkiaSharp::DrawnUi::WinUI::Native::PropertySetExtensions> = L"SkiaSharp.DrawnUi.WinUI.Native.PropertySetExtensions";
    template <> inline constexpr auto& name_v<winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics> = L"SkiaSharp.DrawnUi.WinUI.Native.IBufferExtensionsStatics";
    template <> inline constexpr auto& name_v<winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics> = L"SkiaSharp.DrawnUi.WinUI.Native.IPropertySetExtensionsStatics";
    template <> inline constexpr guid guid_v<winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics>{ 0xDC2FC065,0x16F0,0x5028,{ 0xAF,0xE9,0x1D,0xA5,0x52,0xAD,0x90,0xCA } }; // DC2FC065-16F0-5028-AFE9-1DA552AD90CA
    template <> inline constexpr guid guid_v<winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics>{ 0xCB9E8FFF,0x6848,0x598B,{ 0x8F,0x2A,0x73,0xA2,0x93,0x73,0xE2,0x3F } }; // CB9E8FFF-6848-598B-8F2A-73A29373E23F
    template <> struct abi<winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall GetByteBuffer(void*, int64_t*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall AddSingle(void*, void*, float) noexcept = 0;
            virtual int32_t __stdcall AddSize(void*, void*, winrt::Windows::Foundation::Size) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_SkiaSharp_DrawnUi_WinUI_Native_IBufferExtensionsStatics
    {
        auto GetByteBuffer(winrt::Windows::Storage::Streams::IBuffer const& buffer) const;
    };
    template <> struct consume<winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics>
    {
        template <typename D> using type = consume_SkiaSharp_DrawnUi_WinUI_Native_IBufferExtensionsStatics<D>;
    };
    template <typename D>
    struct consume_SkiaSharp_DrawnUi_WinUI_Native_IPropertySetExtensionsStatics
    {
        auto AddSingle(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, param::hstring const& key, float value) const;
        auto AddSize(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, param::hstring const& key, winrt::Windows::Foundation::Size const& value) const;
    };
    template <> struct consume<winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics>
    {
        template <typename D> using type = consume_SkiaSharp_DrawnUi_WinUI_Native_IPropertySetExtensionsStatics<D>;
    };
}
#endif
