// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_SkiaSharp_DrawnUi_WinUI_Native_2_H
#define WINRT_SkiaSharp_DrawnUi_WinUI_Native_2_H
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Windows.Storage.Streams.1.h"
#include "winrt/impl/SkiaSharp.DrawnUi.WinUI.Native.1.h"
WINRT_EXPORT namespace winrt::SkiaSharp::DrawnUi::WinUI::Native
{
    struct BufferExtensions
    {
        BufferExtensions() = delete;
        static int64_t GetByteBuffer(winrt::Windows::Storage::Streams::IBuffer const& buffer);
    };
    struct PropertySetExtensions
    {
        PropertySetExtensions() = delete;
        static void AddSingle(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, param::hstring const& key, float value);
        static void AddSize(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, param::hstring const& key, winrt::Windows::Foundation::Size const& value);
    };
}
#endif
