// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_SkiaSharp_DrawnUi_WinUI_Native_1_H
#define WINRT_SkiaSharp_DrawnUi_WinUI_Native_1_H
#include "winrt/impl/SkiaSharp.DrawnUi.WinUI.Native.0.h"
WINRT_EXPORT namespace winrt::SkiaSharp::DrawnUi::WinUI::Native
{
    struct WINRT_IMPL_EMPTY_BASES IBufferExtensionsStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBufferExtensionsStatics>
    {
        IBufferExtensionsStatics(std::nullptr_t = nullptr) noexcept {}
        IBufferExtensionsStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IPropertySetExtensionsStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPropertySetExtensionsStatics>
    {
        IPropertySetExtensionsStatics(std::nullptr_t = nullptr) noexcept {}
        IPropertySetExtensionsStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
