// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#include "winrt/SkiaSharp.DrawnUi.WinUI.Native.h"
#include "winrt/Windows.Storage.Streams.h"
namespace winrt::SkiaSharp::DrawnUi::WinUI::Native::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES BufferExtensionsT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics, I...>
    {
        using instance_type = SkiaSharp::DrawnUi::WinUI::Native::BufferExtensions;

        hstring GetRuntimeClassName() const
        {
            return L"SkiaSharp.DrawnUi.WinUI.Native.BufferExtensions";
        }
        auto GetByteBuffer(winrt::Windows::Storage::Streams::IBuffer const& buffer)
        {
            return T::GetByteBuffer(buffer);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}
