// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_SkiaSharp_DrawnUi_WinUI_Native_BufferExtensions()
{
    return winrt::detach_abi(winrt::make<winrt::SkiaSharp::DrawnUi::WinUI::Native::factory_implementation::BufferExtensions>());
}
WINRT_EXPORT namespace winrt::SkiaSharp::DrawnUi::WinUI::Native
{
    int64_t BufferExtensions::GetByteBuffer(winrt::Windows::Storage::Streams::IBuffer const& buffer)
    {
        return SkiaSharp::DrawnUi::WinUI::Native::implementation::BufferExtensions::GetByteBuffer(buffer);
    }
}
