// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#include "winrt/SkiaSharp.DrawnUi.WinUI.Native.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
namespace winrt::SkiaSharp::DrawnUi::WinUI::Native::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES PropertySetExtensionsT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics, I...>
    {
        using instance_type = SkiaSharp::DrawnUi::WinUI::Native::PropertySetExtensions;

        hstring GetRuntimeClassName() const
        {
            return L"SkiaSharp.DrawnUi.WinUI.Native.PropertySetExtensions";
        }
        auto AddSingle(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, hstring const& key, float value)
        {
            return T::AddSingle(propertySet, key, value);
        }
        auto AddSize(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, hstring const& key, winrt::Windows::Foundation::Size const& value)
        {
            return T::AddSize(propertySet, key, value);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}
