// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_SkiaSharp_DrawnUi_WinUI_Native_PropertySetExtensions()
{
    return winrt::detach_abi(winrt::make<winrt::SkiaSharp::DrawnUi::WinUI::Native::factory_implementation::PropertySetExtensions>());
}
WINRT_EXPORT namespace winrt::SkiaSharp::DrawnUi::WinUI::Native
{
    void PropertySetExtensions::AddSingle(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, param::hstring const& key, float value)
    {
        SkiaSharp::DrawnUi::WinUI::Native::implementation::PropertySetExtensions::AddSingle(propertySet, key, value);
    }
    void PropertySetExtensions::AddSize(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, param::hstring const& key, winrt::Windows::Foundation::Size const& value)
    {
        SkiaSharp::DrawnUi::WinUI::Native::implementation::PropertySetExtensions::AddSize(propertySet, key, value);
    }
}
