namespace DrawnUi.Draw;

/// <summary>
/// These are platform-independent. They correspond to JavaScript keys.
/// </summary>
public enum InputKey
{
    Unknown,
    Backspace,
    Tab,
    Enter,
    ShiftLeft,
    ShiftRight,
    ControlLeft,
    ControlRight,
    AltLeft,
    AltRight,
    Pause,
    CapsLock,
    Escape,
    Space,
    PageUp,
    PageDown,
    End,
    Home,
    IntBackslash,
    ArrowLeft,
    ArrowUp,
    ArrowRight,
    ArrowDown,
    PrintScreen,
    Insert,
    Delete,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    MetaLeft,
    MetaRight,
    ContextMenu,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadMultiply,
    NumpadAdd,
    NumpadSubtract,
    NumpadDecimal,
    NumpadDivide,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    NumLock,
    ScrollLock,
    AudioVolumeMute,
    AudioVolumeDown,
    AudioVolumeUp,
    LaunchMediaPlayer,
    LaunchApplication1,
    LaunchApplication2,
    Semicolon,
    Equal,
    Comma,
    Minus,
    Period,
    Slash,
    Backquote,
    BracketLeft,
    Backslash,
    BracketRight,
    Quote,
}

public static class MauiKeyMapper
{
    public static InputKey MapToJava(int code)
    {
        if (KeyValues.TryGetValue(code, out var mapped))
        {
            return mapped;
        }
        return InputKey.Unknown;
    }

    public static int MapToCode(InputKey key)
    {
        if (KeyCodes.TryGetValue(key, out var mapped))
        {
            return mapped;
        }
        return -1;
    }

    static Dictionary<string, int> KeyCodes2 = new()
        {
            { "Backspace", 8 },
            { "Tab", 9 },
            { "Enter", 13 },
            { "ShiftLeft", 16 },
            { "ShiftRight", 16 },
            { "ControlLeft", 17 },
            { "ControlRight", 17 },
            { "AltLeft", 18 },
            { "AltRight", 18 },
            { "Pause", 19 },
            { "CapsLock", 20 },
            { "Escape", 27 },
            { "Space", 32 },
            { "PageUp", 33 },
            { "PageDown", 34 },
            { "End", 35 },
            { "Home", 36 },
            { "ArrowLeft", 37 },
            { "ArrowUp", 38 },
            { "ArrowRight", 39 },
            { "ArrowDown", 40 },
            { "PrintScreen", 44 },
            { "Insert", 45 },
            { "Delete", 46 },
            { "Digit0", 48 },
            { "Digit1", 49 },
            { "Digit2", 50 },
            { "Digit3", 51 },
            { "Digit4", 52 },
            { "Digit5", 53 },
            { "Digit6", 54 },
            { "Digit7", 55 },
            { "Digit8", 56 },
            { "Digit9", 57 },
            { "KeyA", 65 },
            { "KeyB", 66 },
            { "KeyC", 67 },
            { "KeyD", 68 },
            { "KeyE", 69 },
            { "KeyF", 70 },
            { "KeyG", 71 },
            { "KeyH", 72 },
            { "KeyI", 73 },
            { "KeyJ", 74 },
            { "KeyK", 75 },
            { "KeyL", 76 },
            { "KeyM", 77 },
            { "KeyN", 78 },
            { "KeyO", 79 },
            { "KeyP", 80 },
            { "KeyQ", 81 },
            { "KeyR", 82 },
            { "KeyS", 83 },
            { "KeyT", 84 },
            { "KeyU", 85 },
            { "KeyV", 86 },
            { "KeyW", 87 },
            { "KeyX", 88 },
            { "KeyY", 89 },
            { "KeyZ", 90 },
            { "MetaLeft", 91 },
            { "MetaRight", 92 },
            { "ContextMenu", 93 },
            { "Numpad0", 96 },
            { "Numpad1", 97 },
            { "Numpad2", 98 },
            { "Numpad3", 99 },
            { "Numpad4", 100 },
            { "Numpad5", 101 },
            { "Numpad6", 102 },
            { "Numpad7", 103 },
            { "Numpad8", 104 },
            { "Numpad9", 105 },
            { "NumpadMultiply", 106 },
            { "NumpadAdd", 107 },
            { "NumpadSubtract", 109 },
            { "NumpadDecimal", 110 },
            { "NumpadDivide", 111 },
            { "F1", 112 },
            { "F2", 113 },
            { "F3", 114 },
            { "F4", 115 },
            { "F5", 116 },
            { "F6", 117 },
            { "F7", 118 },
            { "F8", 119 },
            { "F9", 120 },
            { "F10", 121 },
            { "F11", 122 },
            { "F12", 123 },
            { "NumLock", 144 },
            { "ScrollLock", 145 },
            { "AudioVolumeMute", 173 },
            { "AudioVolumeDown", 174 },
            { "AudioVolumeUp", 175 },
            { "LaunchMediaPlayer", 181 },
            { "LaunchApplication1", 182 },
            { "LaunchApplication2", 183 },
            { "Semicolon", 186 },
            { "Equal", 187 },
            { "Comma", 188 },
            { "Minus", 189 },
            { "Period", 190 },
            { "Slash", 191 },
            { "Backquote", 192 },
            { "IntBackslash", 192 },            
            { "BracketLeft", 219 },
            { "Backslash", 220 },
            { "BracketRight", 221 },
            { "Quote", 222 },
        };

    static Dictionary<InputKey, int> KeyCodes = new()
    {
    { InputKey.Backspace, 8 },
    { InputKey.Tab, 9 },
    { InputKey.Enter, 13 },
    { InputKey.ShiftLeft, 16 },
    { InputKey.ShiftRight, 16 },
    { InputKey.ControlLeft, 17 },
    { InputKey.ControlRight, 17 },
    { InputKey.AltLeft, 18 },
    { InputKey.AltRight, 18 },
    { InputKey.Pause, 19 },
    { InputKey.CapsLock, 20 },
    { InputKey.Escape, 27 },
    { InputKey.Space, 32 },
    { InputKey.PageUp, 33 },
    { InputKey.PageDown, 34 },
    { InputKey.End, 35 },
    { InputKey.Home, 36 },
    { InputKey.ArrowLeft, 37 },
    { InputKey.ArrowUp, 38 },
    { InputKey.ArrowRight, 39 },
    { InputKey.ArrowDown, 40 },
    { InputKey.PrintScreen, 44 },
    { InputKey.Insert, 45 },
    { InputKey.Delete, 46 },
    { InputKey.Digit0, 48 },
    { InputKey.Digit1, 49 },
    { InputKey.Digit2, 50 },
    { InputKey.Digit3, 51 },
    { InputKey.Digit4, 52 },
    { InputKey.Digit5, 53 },
    { InputKey.Digit6, 54 },
    { InputKey.Digit7, 55 },
    { InputKey.Digit8, 56 },
    { InputKey.Digit9, 57 },
    { InputKey.KeyA, 65 },
    { InputKey.KeyB, 66 },
    { InputKey.KeyC, 67 },
    { InputKey.KeyD, 68 },
    { InputKey.KeyE, 69 },
    { InputKey.KeyF, 70 },
    { InputKey.KeyG, 71 },
    { InputKey.KeyH, 72 },
    { InputKey.KeyI, 73 },
    { InputKey.KeyJ, 74 },
    { InputKey.KeyK, 75 },
    { InputKey.KeyL, 76 },
    { InputKey.KeyM, 77 },
    { InputKey.KeyN, 78 },
    { InputKey.KeyO, 79 },
    { InputKey.KeyP, 80 },
    { InputKey.KeyQ, 81 },
    { InputKey.KeyR, 82 },
    { InputKey.KeyS, 83 },
    { InputKey.KeyT, 84 },
    { InputKey.KeyU, 85 },
    { InputKey.KeyV, 86 },
    { InputKey.KeyW, 87 },
    { InputKey.KeyX, 88 },
    { InputKey.KeyY, 89 },
    { InputKey.KeyZ, 90 },
    { InputKey.MetaLeft, 91 },
    { InputKey.MetaRight, 92 },
    { InputKey.ContextMenu, 93 },
    { InputKey.Numpad0, 96 },
    { InputKey.Numpad1, 97 },
    { InputKey.Numpad2, 98 },
    { InputKey.Numpad3, 99 },
    { InputKey.Numpad4, 100 },
    { InputKey.Numpad5, 101 },
    { InputKey.Numpad6, 102 },
    { InputKey.Numpad7, 103 },
    { InputKey.Numpad8, 104 },
    { InputKey.Numpad9, 105 },
    { InputKey.NumpadMultiply, 106 },
    { InputKey.NumpadAdd, 107 },
    { InputKey.NumpadSubtract, 109 },
    { InputKey.NumpadDecimal, 110 },
    { InputKey.NumpadDivide, 111 },
    { InputKey.F1, 112 },
    { InputKey.F2, 113 },
    { InputKey.F3, 114 },
    { InputKey.F4, 115 },
    { InputKey.F5, 116 },
    { InputKey.F6, 117 },
    { InputKey.F7, 118 },
    { InputKey.F8, 119 },
    { InputKey.F9, 120 },
    { InputKey.F10, 121 },
    { InputKey.F11, 122 },
    { InputKey.F12, 123 },
    { InputKey.NumLock, 144 },
    { InputKey.ScrollLock, 145 },
    { InputKey.AudioVolumeMute, 173 },
    { InputKey.AudioVolumeDown, 174 },
    { InputKey.AudioVolumeUp, 175 },
    { InputKey.LaunchMediaPlayer, 181 },
    { InputKey.LaunchApplication1, 182 },
    { InputKey.LaunchApplication2, 183 },
    { InputKey.Semicolon, 186 },
    { InputKey.Equal, 187 },
    { InputKey.Comma, 188 },
    { InputKey.Minus, 189 },
    { InputKey.Period, 190 },
    { InputKey.Slash, 191 },
    { InputKey.Backquote, 192 },
    { InputKey.BracketLeft, 219 },
    { InputKey.Backslash, 220 },
    { InputKey.BracketRight, 221 },
    { InputKey.Quote, 222 },
    };

    static Dictionary<int, InputKey> KeyValues = new()
    {
        { 8, InputKey.Backspace },
        { 9, InputKey.Tab },
        { 13, InputKey.Enter },
        { 16, InputKey.ShiftLeft },  // or JavaKeyCode.ShiftRight
        { 17, InputKey.ControlLeft },  // or JavaKeyCode.ControlRight
        { 18, InputKey.AltLeft },  // or JavaKeyCode.AltRight
        { 19, InputKey.Pause },
        { 20, InputKey.CapsLock },
        { 27, InputKey.Escape },
        { 32, InputKey.Space },
        { 33, InputKey.PageUp },
        { 34, InputKey.PageDown },
        { 35, InputKey.End },
        { 36, InputKey.Home },
        { 37, InputKey.ArrowLeft },
        { 38, InputKey.ArrowUp },
        { 39, InputKey.ArrowRight },
        { 40, InputKey.ArrowDown },
        { 44, InputKey.PrintScreen },
        { 45, InputKey.Insert },
        { 46, InputKey.Delete },
        { 48, InputKey.Digit0 },
        { 49, InputKey.Digit1 },
        { 50, InputKey.Digit2 },
        { 51, InputKey.Digit3 },
        { 52, InputKey.Digit4 },
        { 53, InputKey.Digit5 },
        { 54, InputKey.Digit6 },
        { 55, InputKey.Digit7 },
        { 56, InputKey.Digit8 },
        { 57, InputKey.Digit9 },
        { 65, InputKey.KeyA },
        { 66, InputKey.KeyB },
        { 67, InputKey.KeyC },
        { 68, InputKey.KeyD },
        { 69, InputKey.KeyE },
        { 70, InputKey.KeyF },
        { 71, InputKey.KeyG },
        { 72, InputKey.KeyH },
        { 73, InputKey.KeyI },
        { 74, InputKey.KeyJ },
        { 75, InputKey.KeyK },
        { 76, InputKey.KeyL },
        { 77, InputKey.KeyM },
        { 78, InputKey.KeyN },
        { 79, InputKey.KeyO },
        { 80, InputKey.KeyP },
        { 81, InputKey.KeyQ },
        { 82, InputKey.KeyR },
        { 83, InputKey.KeyS },
        { 84, InputKey.KeyT },
        { 85, InputKey.KeyU },
        { 86, InputKey.KeyV },
        { 87, InputKey.KeyW },
        { 88, InputKey.KeyX },
        { 89, InputKey.KeyY },
        { 90, InputKey.KeyZ },
        { 91, InputKey.MetaLeft },
        { 92, InputKey.MetaRight },
        { 93, InputKey.ContextMenu },
        { 96, InputKey.Numpad0 },
        { 97, InputKey.Numpad1 },
        { 98, InputKey.Numpad2 },
        { 99, InputKey.Numpad3 },
        { 100, InputKey.Numpad4 },
        { 101, InputKey.Numpad5 },
        { 102, InputKey.Numpad6 },
        { 103, InputKey.Numpad7 },
        { 104, InputKey.Numpad8 },
        { 105, InputKey.Numpad9 },
        { 106, InputKey.NumpadMultiply },
        { 107, InputKey.NumpadAdd },
        { 109, InputKey.NumpadSubtract },
        { 110, InputKey.NumpadDecimal },
        { 111, InputKey.NumpadDivide },
        { 112, InputKey.F1 },
        { 113, InputKey.F2 },
        { 114, InputKey.F3 },
        { 115, InputKey.F4 },
        { 116, InputKey.F5 },
        { 117, InputKey.F6 },
        { 118, InputKey.F7 },
        { 119, InputKey.F8 },
        { 120, InputKey.F9 },
        { 121, InputKey.F10 },
        { 122, InputKey.F11 },
        { 123, InputKey.F12 },
        { 144, InputKey.NumLock },
        { 145, InputKey.ScrollLock },
        { 173, InputKey.AudioVolumeMute },
        { 174, InputKey.AudioVolumeDown },
        { 175, InputKey.AudioVolumeUp },
        { 181, InputKey.LaunchMediaPlayer },
        { 182, InputKey.LaunchApplication1 },
        { 183, InputKey.LaunchApplication2 },
        { 186, InputKey.Semicolon },
        { 187, InputKey.Equal },
        { 188, InputKey.Comma },
        { 189, InputKey.Minus },
        { 190, InputKey.Period },
        { 191, InputKey.Slash },
        { 192, InputKey.Backquote },
        { 219, InputKey.BracketLeft },
        { 220, InputKey.Backslash },
        { 221, InputKey.BracketRight },
        { 222, InputKey.Quote },
    };


}





