// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_SkiaSharp_DrawnUi_WinUI_Native_H
#define WINRT_SkiaSharp_DrawnUi_WinUI_Native_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.230706.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.230706.1"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.Storage.Streams.2.h"
#include "winrt/impl/SkiaSharp.DrawnUi.WinUI.Native.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_SkiaSharp_DrawnUi_WinUI_Native_IBufferExtensionsStatics<D>::GetByteBuffer(winrt::Windows::Storage::Streams::IBuffer const& buffer) const
    {
        int64_t result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics)->GetByteBuffer(*(void**)(&buffer), &result));
        return result;
    }
    template <typename D> auto consume_SkiaSharp_DrawnUi_WinUI_Native_IPropertySetExtensionsStatics<D>::AddSingle(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, param::hstring const& key, float value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics)->AddSingle(*(void**)(&propertySet), *(void**)(&key), value));
    }
    template <typename D> auto consume_SkiaSharp_DrawnUi_WinUI_Native_IPropertySetExtensionsStatics<D>::AddSize(winrt::Windows::Foundation::Collections::PropertySet const& propertySet, param::hstring const& key, winrt::Windows::Foundation::Size const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics)->AddSize(*(void**)(&propertySet), *(void**)(&key), impl::bind_in(value)));
    }
    template <typename D>
    struct produce<D, winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics> : produce_base<D, winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics>
    {
        int32_t __stdcall GetByteBuffer(void* buffer, int64_t* result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *result = detach_from<int64_t>(this->shim().GetByteBuffer(*reinterpret_cast<winrt::Windows::Storage::Streams::IBuffer const*>(&buffer)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics> : produce_base<D, winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics>
    {
        int32_t __stdcall AddSingle(void* propertySet, void* key, float value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().AddSingle(*reinterpret_cast<winrt::Windows::Foundation::Collections::PropertySet const*>(&propertySet), *reinterpret_cast<hstring const*>(&key), value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall AddSize(void* propertySet, void* key, winrt::Windows::Foundation::Size value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().AddSize(*reinterpret_cast<winrt::Windows::Foundation::Collections::PropertySet const*>(&propertySet), *reinterpret_cast<hstring const*>(&key), *reinterpret_cast<winrt::Windows::Foundation::Size const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::SkiaSharp::DrawnUi::WinUI::Native
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::SkiaSharp::DrawnUi::WinUI::Native::IBufferExtensionsStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::SkiaSharp::DrawnUi::WinUI::Native::IPropertySetExtensionsStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::SkiaSharp::DrawnUi::WinUI::Native::BufferExtensions> : winrt::impl::hash_base {};
    template<> struct hash<winrt::SkiaSharp::DrawnUi::WinUI::Native::PropertySetExtensions> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
